# Generated by Django 5.0.1 on 2026-02-05 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Team name (must be unique)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Team description and purpose')),
                ('is_active', models.BooleanField(default=True, help_text='Active teams are visible to members')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(help_text='Team leader who created and manages the team', limit_choices_to={'role__in': ['team_leader', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='When user joined the team')),
                ('member', models.ForeignKey(help_text='User who is a member of the team', on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(help_text='Team this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.team')),
            ],
            options={
                'verbose_name': 'Team Membership',
                'verbose_name_plural': 'Team Memberships',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='users_team_name_a3740c_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['leader'], name='users_team_leader__c2c9df_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['is_active'], name='users_team_is_acti_3dd195_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team', 'member'], name='users_teamm_team_id_2eaec8_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team'], name='users_teamm_team_id_fbaa06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together={('team', 'member')},
        ),
    ]
