# Generated by Django 5.0.1 on 2026-02-05 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_team_teammembership_team_users_team_name_a3740c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title or name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed task description')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Task priority level', max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('review', 'Review'), ('completed', 'Completed')], default='not_started', help_text='Current task status', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, help_text='Task due date and time', null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for organization', max_length=200)),
                ('is_urgent', models.BooleanField(default=False, help_text='Mark task as urgent/flagged')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Team member this task is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Team leader who created this task', on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(help_text='Team this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.team')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Attachment file', upload_to='task_attachments/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(help_text='Task this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='users.task')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this file', on_delete=django.db.models.deletion.CASCADE, related_name='task_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Attachment',
                'verbose_name_plural': 'Task Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Comment text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(help_text='Task this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.task')),
                ('user', models.ForeignKey(help_text='User who posted the comment', on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Comment',
                'verbose_name_plural': 'Task Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['team', 'status'], name='users_task_team_id_d76530_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='users_task_assigne_409c22_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='users_task_due_dat_56ac82_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='users_task_priorit_605793_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['team', 'created_at'], name='users_task_team_id_afd1e8_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['task'], name='users_taska_task_id_f40f08_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['uploaded_by'], name='users_taska_uploade_5fb68b_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task', 'created_at'], name='users_taskc_task_id_2d0ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['user'], name='users_taskc_user_id_399585_idx'),
        ),
    ]
