# Generated by Django 5.0.1 on 2026-02-06 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_task_taskattachment_taskcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('task_assigned', models.BooleanField(default=True, help_text='Notify when task is assigned')),
                ('status_changed', models.BooleanField(default=True, help_text='Notify when task status changes')),
                ('comment_added', models.BooleanField(default=True, help_text='Notify when comment is added to your task')),
                ('deadline_approaching', models.BooleanField(default=True, help_text='Notify when deadline is approaching (24 hours)')),
                ('task_overdue', models.BooleanField(default=True, help_text='Notify when task becomes overdue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User this preference belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('status_changed', 'Status Changed'), ('comment_added', 'Comment Added'), ('deadline_approaching', 'Deadline Approaching'), ('task_overdue', 'Task Overdue')], help_text='Type of notification', max_length=30)),
                ('message', models.TextField(help_text='Notification message')),
                ('is_read', models.BooleanField(default=False, help_text='Whether notification has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, help_text='Related task (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.task')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='users_notif_recipie_2469dd_idx'), models.Index(fields=['recipient', 'created_at'], name='users_notif_recipie_17b29e_idx'), models.Index(fields=['task'], name='users_notif_task_id_e31749_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('assigned', 'Assigned'), ('commented', 'Commented'), ('attachment_added', 'Attachment Added'), ('edited', 'Edited'), ('deleted', 'Deleted')], help_text='Type of activity', max_length=30)),
                ('description', models.TextField(help_text='Description of what changed')),
                ('old_value', models.TextField(blank=True, help_text='Previous value (for changes)')),
                ('new_value', models.TextField(blank=True, help_text='New value (for changes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(help_text='Task this activity is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='users.task')),
                ('user', models.ForeignKey(help_text='User who performed this action', on_delete=django.db.models.deletion.PROTECT, related_name='task_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Activity',
                'verbose_name_plural': 'Task Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', 'created_at'], name='users_taska_task_id_67c552_idx'), models.Index(fields=['user'], name='users_taska_user_id_c3b451_idx'), models.Index(fields=['activity_type'], name='users_taska_activit_8e9dfe_idx')],
            },
        ),
    ]
